### ISSUE TITLE
(longer term) add hard/versus soft reserve to the configuration for a reserve category

### ISSUE THREAD

**Issue by cpatel-seii** [JohnEFerguson/project-reserve#139]
This will be a checkbox and an (i) button on the add reserve category page. Could also be an element in the reserve category table. 

**Backend:**

If hard reserve, we do as is currently implemented.

If soft reserve, when looping through reserve categories we include all patients when walking through the sorted list. An additional item is added to the sort - 1 if the patient belong to the reserve category and 2 if the patient does not. In this way, patients who are not eligible for reserve category X are still able to receive some of reserve Category X's units (e.g. no wastefulness)

**Comment by JohnEFerguson** [comment]
track leftover per reserve category

**Comment by cpatel-seii** [comment]
Let's kill the longer term goal here - leftover per reserve category looks good @JohnEFerguson, thanks!
