### ISSUE TITLE
validation on data file uploaded for non-required patient fields

### ISSUE THREAD

**Issue by cpatel-seii** [JohnEFerguson/project-reserve#153]
If a field does not apply to a patient, the patient should not have to have a correct or filled-in value for that field. Right now, this is rejected in upload validation.

**Comment by sgrund14** [comment]
@cpatel-seii do you mean that for non-required fields we are validating them as if they are required?

**Comment by cpatel-seii** [comment]
@sgrund14 yes exactly

**Comment by cpatel-seii** [comment]
@sgrund14 I think the update works but now the required field is not always validated re missing or not. For example, see below: the ``clinical_trial_participant`` category requires ``age`` but the upload validation allowed an upload with ``age`` missing

![image](https://user-images.githubusercontent.com/65291323/104930780-9c1a1c00-5973-11eb-8758-9e1d4a8c1a5a.png)

![image](https://user-images.githubusercontent.com/65291323/104930891-b3590980-5973-11eb-87f6-49f7a84c5cf7.png)

**Comment by sgrund14** [comment]
@cpatel-seii can you try this again with the updated build? it should be working 🤔

**Comment by cpatel-seii** [comment]
@sgrund14 @JohnEFerguson Just tried again and still an old build I think - this might be because I am using Windows, is the Mac OS the one with the most up to date build?

**Comment by sgrund14** [comment]
i just tested the latest mac DMG and am also seeing old code, wonder if it's a versioning issue which caches code perhaps?

**Comment by cpatel-seii** [comment]
@sgrund14 That is a good point - I will try clearing some things out later today on the old version

**Comment by cpatel-seii** [comment]
@sgrund14 - I think this is not working, in the below case Patient 2 who qualifies for the ``hard_hit_area`` reserve category should be required to input age. Under the below config / upload, the data is successfully uploaded.

![image](https://user-images.githubusercontent.com/65291323/105603095-889bf600-5d63-11eb-9dc0-9810fca343cc.png)

![image](https://user-images.githubusercontent.com/65291323/105603336-9b162f80-5d63-11eb-9784-eb3d2c36e6b9.png)

**Comment by sgrund14** [comment]
@cpatel-seii does it say it is required in the finish & confirm screen?

**Comment by sgrund14** [comment]
i think we are only ever requiring patient id + the `is_eligible_for_` fields

so if we aren't validating those fields, they aren't required (by the app logic, at least)

cc @JohnEFerguson

**Comment by JohnEFerguson** [comment]
@cpatel-seii @sgrund14  this level of validation was not in the scope of the original design, though I see how it might make sense. It's possible to implement but would take significant effort as it does not fit naturally into the current structure of the backend process

**Comment by cpatel-seii** [comment]
@sgrund14 @JohnEFerguson this all makes sense, my vote is to not implement this level of validation but add some warning that allocation behavior will not be as one might expect in the presence of missing data or something

How do you both feel about that? If you agree, I would propose adding it to the Finish & Confirm page

**Comment by cpatel-seii** [comment]
@sgrund14 @JohnEFerguson bumping this

**Comment by sgrund14** [comment]
i can add a little warning, want to send over come copy?

**Comment by cpatel-seii** [comment]
@sgrund14 thanks! How about something along the below to be put as a third paragraph:

"As a warning, allocation behavior may not proceed as intended in the presence of missing required data."

**Comment by cpatel-seii** [comment]
Looks good, thanks!
