### ISSUE TITLE
Error message on data upload format

### ISSUE THREAD

**Issue by cpatel-seii** [JohnEFerguson/project-reserve#154]
Instead of "Error: Patient X" should say "Error: Patient in row XX"

**Comment by cpatel-seii** [comment]
@sgrund14 This issue is of the lowest priority / doesn't matter at all but the error message syntax is still the "Error: Patient X" version

![image](https://user-images.githubusercontent.com/65291323/104931505-7d685500-5974-11eb-800c-d07a99023702.png)

**Comment by sgrund14** [comment]
this shouldn't be happening:

https://github.com/JohnEFerguson/project-reserve/blob/e9e4d1f32521ffd626942fa3e345dd3859d1ade6/src/public/pages/load-data.vue#L208-L210

are we sure you are using a build from the latest master? cc @JohnEFerguson

**Comment by cpatel-seii** [comment]
Looks good @sgrund14 - thanks!
