### ISSUE TITLE
in print of allocation output, minor change to text (or updating of print function to output new item)

### ISSUE THREAD

**Issue by cpatel-seii** [JohnEFerguson/project-reserve#157]
In the "Number Allocated" row of the output file, if there was a global supply of 2 and only 1 was allocated, I am seeing "Number Allocated: 2", "Units Left Over: 1". I think this is either because the "Number Allocated" is mislabeled (which is my bad) and should be "Total Supply Rationed" or it is because the print method is showing the global supply rather than the number of allocations made. Either way this is minor.

![image](https://user-images.githubusercontent.com/65291323/103095704-90834180-45cf-11eb-8674-6a409ccb1166.png)

**Comment by cpatel-seii** [comment]
@sgrund14 I am still seeing the same issue (see below screenshot, global supply in the configuration was 120, 105 were allocated, and 15 were left over) - can we either (a) change "Number Allocated" to "Total Supply Rationed" or (b) print 120 - 15 = 105 under number allocated?

![image](https://user-images.githubusercontent.com/65291323/104933748-4a739080-5977-11eb-82d7-d5d10e483b76.png)

**Comment by sgrund14** [comment]
@cpatel-seii ok now i'm pretty sure you are using an old build haha, this one is definitely fixed by the latest version. did @JohnEFerguson upload the new version to AWS?

**Comment by cpatel-seii** [comment]
Looks good @sgrund14 - thanks!
